import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";
import react from "@vitejs/plugin-react";
import { themeBootstrap } from "./public/theme.js";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = async name => fs.readFile(path.join(here, "public", name), "utf8");
const bundle = async entry => (await esbuild({
  entryPoints: [path.join(here, entry)],
  bundle: true,
  write: false,
  format: "iife",
  target: "es2022",
  minify: true,
  loader: { ".png": "dataurl" }
})).outputFiles[0].text;
const escapeScript = value => value.replace(/<\/script/gi, "<\\/script");

const legacyScript = await bundle("public/operator.js");
const bridge = await bundle("mcp-bridge.js");
const relayIcon = "data:image/png;base64," + (await fs.readFile(path.join(here, "public/brand/relay.png"))).toString("base64");
const legacyCss =
  await source("operator.css") + "\n" +
  await fs.readFile(path.join(here, "../../packages/shared-ui/tokens.css"), "utf8") + "\n" +
  await fs.readFile(path.join(here, "../../packages/shared-ui/components.css"), "utf8") + "\n" +
  await source("operator-1.8.css") + "\n" +
  await source("qa.css");

let inspectorHtml = (await source("index.html"))
  .replaceAll("__RELAY_ICON__", relayIcon)
  .replace("__RELAY_THEME_BOOTSTRAP__", () => "<script>(" + themeBootstrap.toString() + ")()</script>")
  .replace(/<link rel="stylesheet" href="\/(?:operator|operator-1\\.8|qa).css">/g, "")
  .replace("<title>relay</title>", "<title>relay inspector</title>")
  .replace("</head>", () => "<style>" + legacyCss + "</style><script>if(!location.hash)location.replace(location.pathname+'#review')</script></head>");

const viteResult = await viteBuild({
  root: here,
  configFile: false,
  publicDir: false,
  plugins: [react()],
  logLevel: "silent",
  build: {
    write: false,
    sourcemap: false,
    minify: "esbuild",
    cssCodeSplit: false,
    assetsInlineLimit: Number.MAX_SAFE_INTEGER,
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
        entryFileNames: "assets/relay-2.0.js",
        chunkFileNames: "assets/relay-2.0-[name].js",
        assetFileNames: asset => asset.name?.endsWith(".css") ? "assets/relay-2.0.css" : "assets/[name][extname]"
      }
    }
  }
});
const outputs = (Array.isArray(viteResult) ? viteResult : [viteResult]).flatMap(output => output.output || []);
const htmlAsset = outputs.find(item => item.type === "asset" && item.fileName === "index.html");
const jsChunk = outputs.find(item => item.type === "chunk" && item.isEntry);
const cssAsset = outputs.find(item => item.type === "asset" && item.fileName.endsWith(".css"));
if (!htmlAsset || !jsChunk || !cssAsset) throw new Error("Relay 2.0 Vite build did not emit the expected HTML, JS and CSS assets.");

const brandNames = ["relay", "today", "runner", "inspector", "night-shift"];
const brandUrls = Object.fromEntries(await Promise.all(brandNames.map(async name => [
  "/brand/" + name + ".png",
  "data:image/png;base64," + (await fs.readFile(path.join(here, "public/brand", name + ".png"))).toString("base64")
])));
const inlineBrandUrls = value => {
  let next = String(value);
  for (const [url, data] of Object.entries(brandUrls)) next = next.replaceAll(url, data);
  return next;
};

const reactHtml = String(htmlAsset.source);
const reactJs = inlineBrandUrls(jsChunk.code);
const reactCss = String(cssAsset.source);
const mcpHtml = reactHtml
  .replace(/<link rel="stylesheet"[^>]*href="\/assets\/[^"]+\.css"[^>]*>/, () => "<style>" + reactCss + "</style>")
  .replace(/<script type="module"[^>]*src="\/assets\/[^"]+\.js"><\/script>/, () => "<script type=\"module\">" + escapeScript(bridge + "\n" + reactJs) + "</script>");

const webAssets = {
  "/": { type: "text/html; charset=utf-8", text: reactHtml },
  "/index.html": { type: "text/html; charset=utf-8", text: reactHtml },
  ["/" + jsChunk.fileName]: { type: "text/javascript; charset=utf-8", text: reactJs },
  ["/" + cssAsset.fileName]: { type: "text/css; charset=utf-8", text: reactCss },
  "/inspector": { type: "text/html; charset=utf-8", text: inspectorHtml },
  "/inspector/": { type: "text/html; charset=utf-8", text: inspectorHtml },
  "/relay-app.js": { type: "text/javascript; charset=utf-8", text: legacyScript }
};

await fs.writeFile(
  path.join(here, "generated.js"),
  "// Generated by apps/web/build.mjs from the Relay 2.0 React app and preserved Inspector surface.\n" +
  "export const webAssets = " + JSON.stringify(webAssets) + ";\n" +
  "export const mcpHtml = " + JSON.stringify(mcpHtml) + ";\n"
);
console.log("Built Relay 2.0 React web/MCP surface + preserved Inspector");
