// Generated by apps/web/build.mjs from split Relay React + Inspector payloads.
import { reactHtml, reactJs, reactCss, bridge } from "./generated-react.js";
import { inspectorHtml, legacyScript } from "./generated-inspector.js";
const escapeScript=value=>value.replace(/<\/script/gi,"<\\/script");
export const webAssets={"/":{type:"text/html; charset=utf-8",text:reactHtml},"/index.html":{type:"text/html; charset=utf-8",text:reactHtml},"/assets/relay-2.0.js":{type:"text/javascript; charset=utf-8",text:reactJs},"/assets/relay-2.0.css":{type:"text/css; charset=utf-8",text:reactCss},"/inspector":{type:"text/html; charset=utf-8",text:inspectorHtml},"/inspector/":{type:"text/html; charset=utf-8",text:inspectorHtml},"/relay-app.js":{type:"text/javascript; charset=utf-8",text:legacyScript}};
export const mcpHtml=reactHtml.replace("<link rel=\"stylesheet\" crossorigin href=\"/assets/relay-2.0.css\">","<style>"+reactCss+"</style>").replace("<script type=\"module\" crossorigin src=\"/assets/relay-2.0.js\"></script>","<script type=\"module\">"+escapeScript(bridge+"\n"+reactJs)+"</script>");
