import { useEffect, useState, type CSSProperties } from 'react';
import { useLiveRelay } from '../live';
import { projectLabel } from '../api';
import { telemetryModel } from '../../public/telemetry-model.js';
const colors=['#f58f76','#46caa0','#efb65d'];
function Icon({kind}:{kind:'play'|'eye'|'target'|'activity'|'pause'}){return <span className={'telemetry-icon icon-'+kind}><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='play'?<path d="m11 7 15 9-15 9Z"/>:kind==='eye'?<><path d="M3 16s5-9 13-9 13 9 13 9-5 9-13 9S3 16 3 16Z"/><circle cx="16" cy="16" r="4"/></>:kind==='target'?<><circle cx="16" cy="16" r="12"/><circle cx="16" cy="16" r="7"/><circle cx="16" cy="16" r="2"/></>:kind==='pause'?<><path d="M12 8v16M21 8v16"/></>:<path d="m4 24 8-12 9 8 7-14"/>}</svg></span>}
function Ring({percent,value,caption}:{percent:number|null;value:string;caption:string}){return <div className="telemetry-ring" aria-label={value+' '+caption}><svg viewBox="0 0 220 220" aria-hidden="true"><circle className="telemetry-track" cx="110" cy="110" r="94"/><circle className="telemetry-arc" cx="110" cy="110" r="94" pathLength="100" strokeDasharray={`${percent??0} 100`} opacity={percent?1:0}/></svg><div><strong key={value}>{value}</strong><span>{caption}</span></div></div>}
export function LiveTelemetry(){
 const {allSnapshot:snapshot,state,eventConnected,refresh}=useLiveRelay();const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const model=telemetryModel(snapshot,now),ready=Boolean(snapshot)&&!snapshot?.loadingProgress?.length&&!snapshot?.failedProgress?.length;
 const age=snapshot?Math.max(0,Math.floor((now-Date.parse(snapshot.fetchedAt))/1000)):null;
 const live=ready&&state==='live'&&age!==null&&age<90;
 const known=ready&&Boolean(snapshot?.workload),value=known&&model.percent!==null?model.percent+'%':'—';
 const max=Math.max(3,Math.ceil(Math.max(...model.bins)/3)*3),points=model.bins.map((n,i)=>[32+i*48,164-n/max*124]),line=points.map(([x,y],i)=>i?`C${(points[i-1][0]+x)/2},${points[i-1][1]} ${(points[i-1][0]+x)/2},${y} ${x},${y}`:`M${x},${y}`).join(' '),area=line+' L560,164 L32,164 Z';
 const href=(project:string,id?:string)=>'https://ctrl.loew.fi/#/runner'+(id?'/'+encodeURIComponent(project)+'/'+encodeURIComponent(id):'?project='+encodeURIComponent(project));
 return <section className="live-telemetry" aria-label="Live workspace telemetry" data-live={live}>
  <div className="telemetry-heading"><h2>your workspace <span>/ now</span></h2><button className="telemetry-freshness" type="button" onClick={()=>void refresh()} aria-label="Refresh workspace telemetry"><i/>{live?eventConnected?'Live':'Auto refresh':snapshot?state==='reconnecting'?'Refreshing':'Partial or stale':'Connecting'}<span>{age===null?'waiting for records':age<60?`${age}s ago`:`${Math.floor(age/60)}m ago`}</span></button></div>
  <div className="telemetry-mosaic">
   <article className="telemetry-card telemetry-progress"><header><Icon kind="play"/><div><h3>today’s progress</h3><p>{known?`${model.completed} completed today · ${model.open} still open`:'Reading current work records…'}</p></div></header><div className="telemetry-progress-body"><Ring percent={known?model.percent:null} value={value} caption={known&&model.total?`${model.completed} of ${model.total} work items complete`:'No measurable work yet'}/><div className="telemetry-states">{[{kind:'play' as const,count:model.moving.length,label:'moving',color:colors[1]},{kind:'pause' as const,count:model.waiting.length,label:'waiting',color:colors[2]}].map(group=><div className="telemetry-state" key={group.label} style={{'--signal':group.color} as CSSProperties}><Icon kind={group.kind}/><div><strong key={group.count}>{ready?group.count:'—'}</strong> {group.label}<div className="telemetry-meter" aria-label={`${group.count} of ${model.items.length} observed work items ${group.label}`}><span style={{width:ready&&model.items.length?`${group.count/model.items.length*100}%`:'0%'}}/></div></div></div>)}</div></div><p className="telemetry-note">Completion recorded in Relay. Includes open work and items completed today.</p></article>
   <article className="telemetry-card telemetry-needs"><header><Icon kind="eye"/><div><h3>needs you</h3><p>{ready?model.needs.length?`${model.needs.length} items need your attention.`:'Nothing is waiting for your input.':'Checking requests for your input…'}</p></div><strong className="telemetry-number" key={model.needs.length}>{ready?model.needs.length:'—'}</strong></header><div className="telemetry-attention-list">{model.needs.slice(0,2).map(item=><a href={href(item.project,item.assignment)} key={item.project+item.assignment}><i/><div><strong>{projectLabel(item.project)}</strong><span>{item.waiting_reason||item.next_action||item.goal}</span></div><b aria-hidden="true">→</b></a>)}{ready&&!model.needs.length&&<div className="telemetry-empty">You’re clear. New requests will appear here.</div>}{model.needs.length>2&&<a className="telemetry-more" href="https://ctrl.loew.fi/#/runner">See all {model.needs.length} requests →</a>}</div></article>
   <article className="telemetry-card telemetry-motion"><header><Icon kind="target"/><div><h3>in motion</h3><p>{ready?`${model.projects.length} products with observed activity.`:'Reading product activity…'}</p></div></header><div className="telemetry-motion-body"><div className="telemetry-orbits" aria-label="Products share of observed moving work"><svg viewBox="0 0 220 220" aria-hidden="true">{[94,78,62].map((radius,i)=><g key={radius}><circle className="telemetry-track" cx="110" cy="110" r={radius}/><circle className="telemetry-project-arc" cx="110" cy="110" r={radius} pathLength="100" stroke={colors[i]} opacity={ready&&model.projects[i]?1:0} strokeDasharray={`${ready&&model.projects[i]?model.projects[i].count/model.moving.length*100:0} 100`}/></g>)}</svg><div><strong key={model.projects.length}>{ready?model.projects.length:'—'}</strong><span>active<br/>products</span></div></div><div className="telemetry-projects">{model.projects.slice(0,3).map((item,i)=><a href={href(item.project)} key={item.project}><i style={{background:colors[i]}}/><div><strong>{projectLabel(item.project)}</strong><span>{item.count} moving {item.count===1?'item':'items'}</span></div><b aria-hidden="true">→</b></a>)}{ready&&!model.projects.length&&<p>No current movement reported.</p>}</div></div><p className="telemetry-note">Rings show each product’s share of moving work.</p></article>
   <article className="telemetry-card telemetry-activity"><header><Icon kind="activity"/><div><h3>activity</h3><p>{model.events} observed updates in the last 6 hours.</p></div><strong className="telemetry-number" key={model.events}>{model.events}<small>updates</small></strong></header><div className="telemetry-chart" role="img" aria-label={`Observed updates per half hour, oldest first: ${model.bins.join(', ')}. ${ready?'Current loaded records':'Partial records; coverage incomplete'}.`}><svg viewBox="0 0 588 208"><defs><linearGradient id="telemetry-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f58f76" stopOpacity=".24"/><stop offset="100%" stopColor="#f58f76" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><g key={i}><path className="telemetry-gridline" d={`M32 ${164-i*41.33}H560`}/><text x="6" y={168-i*41.33}>{Math.round(max*i/3)}</text></g>)}<path d={area} fill="url(#telemetry-area)"/><path className="telemetry-chart-line" d={line}/>{points.map(([x,y],i)=><circle key={i} className={i===11&&live&&model.bins[i]>0?'telemetry-latest-point':''} cx={x} cy={y} r={model.bins[i]?3.8:0} fill="#f8d5c9" stroke="#f58f76" strokeWidth="2"/>)}{['6h ago','4h','2h','now'].map((text,i)=><text key={text} x={32+i*176} y="197" textAnchor={i===3?'end':'start'}>{text}</text>)}</svg></div><p className="telemetry-note">{eventConnected?'Connected to live updates.':'Refreshes every minute.'} Source, check and deployment events.</p></article>
  </div>
 </section>;
}
