import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
const root = new URL('../', import.meta.url);
const hash = text => createHash('sha256').update(text).digest('hex');
const files = [];
async function walk(directory) {
  for (const entry of (await fs.readdir(new URL(directory, root), { withFileTypes: true })).sort((a,b)=>a.name.localeCompare(b.name))) {
    const relative = path.posix.join(directory, entry.name);
    if (entry.isSymbolicLink()) throw Error('Skill sources cannot be symlinks');
    if (entry.isDirectory()) await walk(relative + '/');
    else if (entry.name.endsWith('.md')) files.push(relative);
  }
}
await walk('skills/');
const bundles = [];
for (const file of files) {
  const raw = await fs.readFile(new URL(file, root), 'utf8');
  const name = file.replace(/^skills\//,'').replace(/\/SKILL\.md$/,'').replace(/\.md$/,'').replaceAll('/','.').replaceAll('_','-').toLowerCase();
  const id = 'relay.' + name;
  const text = raw.startsWith('---\n') ? raw : `---\nname: ${id}\ndescription: ${raw.split('\n').find(line=>line.trim())?.replace(/^#+\s*/, '') || name}\n---\n\n${raw}`;
  const platform = ['macos','windows','android','gnome','web'].find(x=>name.includes(x));
  const manifest = { id, name: name.replaceAll('.',' '), version: '1.0.0', origin: 'relay', license: 'LicenseRef-Relay-Private',
    provenance: { source: 'https://github.com/lrnolivia/relay/' + file, revision: 'sha256:' + hash(raw) },
    integrity: 'sha256:' + hash(text), entrypoint: 'SKILL.md', context_budget: Math.max(256, Math.ceil(Buffer.byteLength(text)/4)),
    tags: [...new Set(name.split(/[.-]/))], dependencies: [], required_capabilities: name.includes('figma') ? ['figma'] : [],
    optional_capabilities: [], platforms: platform ? [platform] : ['generic'], staff_affinities: [], update_policy: 'pinned', executable: false };
  bundles.push({ manifest, text });
}
await fs.writeFile(new URL('src/skills-bundles.js',root),'// Generated by scripts/build-skills.mjs from canonical skill sources.\nexport const SKILL_BUNDLES = '+JSON.stringify(bundles,null,2)+';\n');
console.log(`Built ${bundles.length} portable, integrity-bound skill bundles`);
