import assert from 'node:assert/strict';
import {request} from 'node:https';
import {randomBytes,createHash} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const origin='https://ctrl.loew.fi',relay='https://relay.loew.fi';
const expected='887d31efa085f878a21837b906079b2f7169371a';
const headers={'CF-Access-Client-Id':process.env.CF_ACCESS_CLIENT_ID,'CF-Access-Client-Secret':process.env.CF_ACCESS_CLIENT_SECRET};
assert.ok(Object.values(headers).every(Boolean),'Existing Access service identity required');
const out='qa-evidence/ctrl-production';await mkdir(out,{recursive:true});
async function read(url,options={}){const r=await fetch(url,{headers,redirect:'manual',signal:AbortSignal.timeout(20000),...options});assert.ok(r.ok,`${new URL(url).pathname}: HTTP ${r.status}`);return r;}
const anonymous=await fetch(origin+'/',{redirect:'manual',signal:AbortSignal.timeout(20000)});assert.ok([302,303,307,401,403].includes(anonymous.status),'Anonymous visitor must not receive application');
const build=await (await read(origin+'/build.json')).json();assert.equal(build.source_sha,expected);
const icon=Buffer.from(await(await read(origin+'/brand/ctrl.png')).arrayBuffer());assert.equal(createHash('sha256').update(icon).digest('hex'),'0c8ede34b73f061ed8dfeb6585206e53db1b2fb101e4addda6fa67fbd4fbb153');
for(const p of ['/api/projects','/api/workers','/api/relay-info'])await read(origin+p);
function connect(cursor){return new Promise((resolve,reject)=>{const events=[],listeners=[];let pending=Buffer.alloc(0);const key=randomBytes(16).toString('base64');const req=request(origin+'/api/events'+(cursor?'?cursor='+cursor:''),{headers:{...headers,Origin:origin,Connection:'Upgrade',Upgrade:'websocket','Sec-WebSocket-Version':'13','Sec-WebSocket-Key':key}});
const timer=setTimeout(()=>{req.destroy();reject(Error('WebSocket upgrade timed out'));},20000);
req.on('error',reject);req.on('response',res=>{clearTimeout(timer);res.resume();reject(Error('WebSocket HTTP '+res.statusCode));});
req.on('upgrade',(res,socket,head)=>{clearTimeout(timer);assert.equal(res.statusCode,101);assert.equal(res.headers['sec-websocket-accept'],createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64'));
function parse(chunk){pending=Buffer.concat([pending,chunk]);while(pending.length>=2){const opcode=pending[0]&15;let n=pending[1]&127,offset=2;if(n===126){if(pending.length<4)return;n=pending.readUInt16BE(2);offset=4;}else if(n===127){if(pending.length<10)return;n=Number(pending.readBigUInt64BE(2));offset=10;}if(n>65536){socket.destroy();return;}if(pending.length<offset+n)return;const bytes=pending.subarray(offset,offset+n);pending=pending.subarray(offset+n);if(opcode===1){const e=JSON.parse(bytes.toString());events.push(e);for(const f of [...listeners])f(e);}}}
socket.on('data',parse);socket.on('error',()=>{});if(head.length)parse(head);
resolve({events,close:()=>socket.destroy(),wait(predicate){const found=events.find(predicate);if(found)return Promise.resolve(found);return new Promise((yes,no)=>{const f=e=>{if(predicate(e)){clearTimeout(t);listeners.splice(listeners.indexOf(f),1);yes(e);}};const t=setTimeout(()=>{listeners.splice(listeners.indexOf(f),1);no(Error('Expected live invalidation not received'));},15000);listeners.push(f);});}});});req.end();});}
const stream=await connect();const initial=await stream.wait(e=>e.type==='resync');assert.match(initial.cursor,/^\d+$/);
const browser=await chromium.launch({headless:true});const captures=[];
try{for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){const context=await browser.newContext({viewport});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(origin+'/**',route=>route.continue({headers:{...route.request().headers(),...headers}}));const response=await page.goto(origin+'/#/now',{waitUntil:'networkidle'});assert.ok(response.ok());await page.locator('[data-relay-open]:visible').first().click();await page.locator('#relay-engine-panel[open][data-motion="settled"]').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const png=await page.screenshot({fullPage:true});const surface='ctrl-live-'+viewport.width;await writeFile(out+'/'+surface+'.png',png);const metadata={kind:'production_website_verification',target_url:origin+'/',context:{project:'ctrl',environment:'production',surface,commit_sha:expected},engine:'github-chromium',step_label:'Actual protected ctrl Relay panel',viewport,dom:{summary:await page.locator('#relay-engine-panel').innerText()},trace:[{action:'verify_protected_ctrl_panel',url:page.url()}]};const form=new FormData();form.set('metadata',JSON.stringify(metadata));form.set('screenshot',new Blob([png],{type:'image/png'}),surface+'.png');const start=Date.now();const saved=await(await read(relay+'/evidence/ingest',{method:'POST',body:form})).json();const event=await stream.wait(e=>e.type==='change'&&e.at>=start&&e.topics.includes('evidence'));const image=Buffer.from(await(await read(origin+'/api/visual/'+saved.evidence_id+'/image')).arrayBuffer());assert.equal(createHash('sha256').update(image).digest('hex'),createHash('sha256').update(png).digest('hex'));assert.deepEqual(errors,[]);captures.push({surface,evidence_id:saved.evidence_id,event_id:event.id,observed_ms:Date.now()-start});await context.close();}
const resumed=await connect(initial.cursor);const replay=await resumed.wait(e=>e.type==='change'&&BigInt(e.id)>BigInt(initial.cursor));resumed.close();await writeFile(out+'/result.json',JSON.stringify({ok:true,source_sha:expected,build,anonymous_status:anonymous.status,websocket_upgrade:101,replay_id:replay.id,captures},null,2));console.log('CTRL_VERIFIED '+JSON.stringify({source_sha:expected,captures}));}finally{stream.close();await browser.close();}
